security:
  enable_authenticator_manager: true

  # Encoders/Password Hashers
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  # Firewalls
  firewalls:
    dev:
      security: false

    main:
      lazy: true
      provider: app_user_provider
      json_login:
        check_path: /login
        username_path: username
        password_path: password

  # Access Control
  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/profile, roles: ROLE_USER }

  # User Providers
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

